# 추후 구성 이미지 build해서 Docker hub에 공개할 생각도 해야함
tbsen-front-end:
  images: ubuntu24.04:latest

tbsen-back-end:
  images: ubuntu24.04:latest

tbsen-db:
  # 특정 이미지로 고정 필요함
  images: postgresql:latest
    

# 네트워크 구성시 어떻게 해야할지 고민해야함
networks:
  service-net: